spring:
  datasource:
    url: jdbc:sqlite:${app.db-path:logs.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-init-sql: "PRAGMA journal_mode=WAL"
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    cache: false
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

app:
  aws:
    region: us-east-1
    bucket: ""
    prefix: ""
    profile: "default"
  db-path: logs.db
  top-limit: 10
  top-urls-limit: 20

referer-filter:
  self-referers: []

uri-stem-groups:
  groups:
    - name: "WordPress"
      patterns:
        - "/wp-%"
        - "//wp-%"
        - "/wordpress/%"
        - "/wp/%"
    - name: "PHP"
      patterns:
        - "%.php"
        - "%.php7"
    - name: "Feeds"
      patterns:
        - "/feed.xml"
        - "/rss.xml"

uri-stem-filter:
  excluded-extensions:
    - .css
    - .js
    - .svg
    - .avif
    - .ico
    - .png
    - .jpg
    - .jpeg
    - .webp
    - .gif

